services:
  target:
    build: ./target
    tty: true
    stdin_open: true
    environment:
      https_proxy: http://proxy-a:3128

  proxy-a:
    build: ./proxy-a
    tty: true
    stdin_open: true
    volumes:
      - type: bind
        source: "./proxy-a/squid"
        target: "/etc/squid"
    
  proxy-b:
    build: ./proxy-b
    environment:
      TZ: Asia/Tokyo
    volumes:
      - type: bind
        source: "./proxy-b/squid"
        target: "/etc/squid"
