services:
  target:
    build:
      context: ./target
    tty: true
    stdin_open: true
    environment:
      https_proxy: http://proxy-b:3128
    networks:
      - frontend

  proxy-a:
    build:
      context: ./proxy-a
    tty: true
    stdin_open: true
    volumes:
      - type: bind
        source: "./proxy-a/squid"
        target: "/etc/squid"
    networks:
      - frontend
    
  proxy-b:
    build:
      context: ./proxy-b
    environment:
      TZ: Asia/Tokyo
    volumes:
      - type: bind
        source: "./proxy-b/squid"
        target: "/etc/squid"
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
               
